[theme]
backgroundColor = "#ACB5AF" # "#BBD0BA"  # "#C6D2D4" # "#658C72"  # "#042440"
# source: https://www.schemecolor.com/interiors-of-hair-saloon.php
# secondaryBackgroundColor = "#053259"
# textColor="#FFFFFF"
# font="garamont"
